### PR TITLE
 Ask for user guidance when unpushed commits are about to be deployed 

### PR DESCRIPTION
**Pull request by NikosGkotsis**
A prompt for user guidance comes up when there are commits to be
deployed, which have not been pushed to remote master.

Up until now, the prompt was thrown when the head of local
branch was different from remote master's. As a result, user was asked
even if the changes were pushed to remote master but were not the
latest ones.

### CODE REVIEW

**Comment by ctrochalakis** [comment]
Hello Niko,

Thanks for the PR. This change makes it easier to deploy commits that are included in the current master branch. But in the meantime it breaks the confirmation for deploys that have commits that are not present on master, e.g. deploying a completely different branch.

I think we can handle both cases and make it more robust by checking if there are commits that are included in the branch-to-deploy and not in master (`e.g. git log branch-to-deploy ^origin/master`). wdyt?

**Comment by NikosGkotsis** [comment]
>breaks the confirmation for deploys that have commits that are not present on master, e.g. deploying a completely different branch.


This is actually a decision we took since we could not think of such use case. Our view is that commits that are not pushed to remote master, should not be deployed. Are there any use cases we are missing?

**Comment by ctrochalakis** [comment]
> > breaks the confirmation for deploys that have commits that are not present on master, e.g. deploying a completely different branch.
> 
> This is actually a decision we took since we could not think of such use case. Our view is that commits that are not pushed to remote master, should not be deployed. Are there any use cases we are missing?

Yes, we do canary deploys using a not-yet merged branch, e.g. on framework updates or other similar cases.

**Review by vfxcode — APPROVED** [review]
LGTM! but I would suggest you wait for confirmation from @ctrochalakis

**Review by ctrochalakis — APPROVED** [review]
Looks good!

**Pull request merged**
